- name: Include Environment Vars
  ansible.builtin.include_vars:
    file: "{{ environment_type }}_{{ app_type }}.yaml" #Found in vars directory in role

- name: Create Base Workflow
  ansible.tower.tower_workflow_job_template:
    name: Dev Workflow Creator
    inventory: "{{ wf_inventory }}" #Found in vars directory
    state: present

- name: Add Nodes to Workflow
  ansible.tower.tower_workflow_job_template_node:
    inventory: "{{ item.inventory | default(omit) }}"
    unified_job_template: "{{ item.unified_job_template }}"
    credentials: "{{ item.credentials | default(omit) }}"
    identifier: "{{ item.identifier }}"
    always_nodes: "{{ item.always_nodes | default(omit) }}"
    success_nodes: "{{ item.success_nodes | default(omit) }}"
    failure_nodes: "{{ item.failure_nodes | default(omit) }}"
  loop: "{{ wf_structure }}" #found in vars directory

- name: Launch Workflow
  ansible.tower.tower_workflow_launch:
    workflow_template: "Dev Workflow Creator"
    wait: true
  register: workflow_status

- name: Delete Workflow
  ansible.tower.tower_workflow_job_template:
    name: Dev Workflow Creator
    state: absent
